name: clone_weather
version: 1.0.0
publish_to: none
description: Clone of OpenWeather Apps
environment: 
  sdk: '>=2.16.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  bloc: ^8.1.1
  dio: 5.0.3
  flutter_bloc: ^8.1.2
  geocoding: ^2.0.5
  geolocator: ^9.0.2
  lottie: 1.2.2
  flutter:
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

