name: clone_weather
version: 1.0.0
publish_to: none
description: Clone of OpenWeather Apps
environment: 
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  auto_route: ^7.6.0
  cupertino_icons: ^1.0.2
  bloc: ^8.1.2
  code_id_flutter: ^0.1.10
  code_id_network: ^0.1.3
  code_id_storage: ^0.1.7
  dio: ^5.1.2
  equatable: ^2.0.5
  fast_immutable_collections: ^9.1.5
  flutter_bloc: ^8.1.3
  fpdart: ^0.6.0
  freezed_annotation: ^2.2.0
  geocoding: ^2.1.0
  geolocator: ^9.0.2
  get_it: ^7.6.0
  injectable: ^2.1.2
  json_annotation: ^4.8.1
  lottie: ^2.4.0
  flutter:
    sdk: flutter

dev_dependencies:
  auto_route_generator: ^7.1.2
  build_runner: ^2.4.6
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter
  freezed: ^2.3.5
  hive_generator: ^2.0.0
  injectable_generator: ^2.1.6
  json_serializable: ^6.6.1

flutter: 
  uses-material-design: true
  assets:
    - assets/

